const owners = [
  {
    firstName: 'Keriann',
    id: 'f4',
    age: 22,
    gender: 'female',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'Shiba',
    imageUrl: 'https://www.codesmith.io/a8d138452abf02fb0c33903621abef72.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Zac',
    id: 'm4',
    age: 22,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/f60324fb4156adc03fe54114dfcc46e3.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Duygu',
    id: 'f5',
    age: 22,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/41274b47c353894047c8a3f430164fc2.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Sam',
    id: 'm5',
    age: 32,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/c33333bb1fbf62b4b5cac2e0825941df.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Kyle',
    id: 'm0',
    age: 33,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'corgi',
    imageUrl: 'https://www.codesmith.io/dd9f787a9b2c2ac3fe41598e33bf8218.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Victoria',
    id: 'f1',
    age: 30,
    gender: 'female',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'Golden Retriever',
    imageUrl: 'https://www.codesmith.io/121ba6526d3d77425c3a4307922474bf.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Sara',
    id: 'f2',
    age: 28,
    gender: 'female',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'Shiba',
    imageUrl: 'https://www.codesmith.io/5b7c6ff891bdcaab69d244b54c9f3c26.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Phil',
    id: 'm2',
    age: 30,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/050e05f4710f989bebd5507bef701841.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
];

const dogsList = [
  {
    petName: 'Fetch',
    id: 'f30',
    age: 2,
    gender: 'female',
    breed: 'Golden Retriever',
    imageUrl: 'https://www.goodnet.org/photos/281x197/31640_hd.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Recursion',
    id: 'm30',
    age: 2,
    gender: 'male',
    breed: 'corgi',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSFNpUN-gA_T47EP5wU0twV4ly2v2G5Rwz7JQ&usqp=CAU',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Redux',
    id: 'f40',
    age: 2,
    gender: 'female',
    breed: 'Shiba',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmoCWYuhcwzrnrmsTYzHwpW1kjvq2cEQMydA&usqp=CAU',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'SASS',
    id: 'm40',
    age: 2,
    gender: 'male',
    breed: 'French Bulldog',
    imageUrl: 'https://imgix.theurbanlist.com/content/article/dogs-to-follow-on-instagram.png?auto=format,compress&w=520&h=390&fit=crop',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Webpack',
    id: 'f50',
    age: 2,
    gender: 'male',
    breed: 'French Bulldog',
    imageUrl: 'https://www.benjerry.com/files/live/sites/systemsite/files/whats-new/3586-dogs/dog-1b.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Sequal',
    id: 'm50',
    age: 3,
    gender: 'male',
    breed: 'French Bulldog',
    imageUrl: 'https://img.freepik.com/free-photo/adorable-cute-dog-couch_23-2148567061.jpg?size=338&ext=jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Ruby',
    id: 'f10',
    age: 3,
    gender: 'female',
    breed: 'Golden Retriever',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/best-dog-quotes-1580508958.jpg?crop=0.670xw:1.00xh;0.167xw,0&resize=640:*',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Python',
    id: 'f20',
    age: 2,
    gender: 'female',
    breed: 'Shiba',
    imageUrl: 'https://i.pinimg.com/736x/ae/c4/53/aec453161b2f33ffc6219d8a758307a9.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
];

export { owners, dogsList };
