const ownersList = [
  {
    firstName: 'Kyle',
    id: 'm0',
    age: 33,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'corgi',
    imageUrl: 'https://www.codesmith.io/dd9f787a9b2c2ac3fe41598e33bf8218.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Victoria',
    id: 'f1',
    age: 30,
    gender: 'female',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'Golden Retriever',
    imageUrl: 'https://www.codesmith.io/121ba6526d3d77425c3a4307922474bf.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Sara',
    id: 'f2',
    age: 28,
    gender: 'female',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'Shiba',
    imageUrl: 'https://www.codesmith.io/5b7c6ff891bdcaab69d244b54c9f3c26.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Phil',
    id: 'm2',
    age: 30,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/050e05f4710f989bebd5507bef701841.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Allison',
    id: 'f3',
    age: 22,
    gender: 'female',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'Golden Retriever',
    imageUrl: 'https://www.codesmith.io/90fe9e2588745f2d1ac2330112e28658.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Keiran',
    id: 'm3',
    age: 22,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'corgi',
    imageUrl: 'https://www.codesmith.io/9f9e6903a9bba63891bbc6813c35ebc0.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Keriann',
    id: 'f4',
    age: 22,
    gender: 'female',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'Shiba',
    imageUrl: 'https://www.codesmith.io/a8d138452abf02fb0c33903621abef72.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Zac',
    id: 'm4',
    age: 22,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/f60324fb4156adc03fe54114dfcc46e3.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Duygu',
    id: 'f5',
    age: 22,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/41274b47c353894047c8a3f430164fc2.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    firstName: 'Sam',
    id: 'm5',
    age: 32,
    gender: 'male',
    email: 'asdf@gmail.com',
    password: 'test123',
    dog: 'French Bulldog',
    imageUrl: 'https://www.codesmith.io/c33333bb1fbf62b4b5cac2e0825941df.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
];

const tripsList = [
  {
    title: 'To The Mountain',
    imageUrl: 'https://www.urbanpethospital.com/blog/image.axd?picture=/hiking-with-dog.jpg',
    tripId: '1',
    price: '99',
    detailsUrl: '/trips/1',
    destination: 'Catskill Falls',
    dogs: [],
    owners: [],
    date: '09/14/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Codesmith Farm', '4PM Amish Museum', '6PM Back to NYC'],
  },
  {
    title: 'To The Beach',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0995/5684/files/Image-1_large.jpg?v=1490124277',
    tripId: '2',
    detailsUrl: '/trips/2',
    price: '99',
    destination: 'Sandyhook Beach',
    dogs: [],
    owners: [],
    date: '08/28/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Sandyhook Beach', '4PM Amish Museum', '6PM Back to NYC'],
  },
  {
    title: 'Pick Some Apples',
    imageUrl: 'https://107fclzizww4ftn03ydjxa1a-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/apples.jpg',
    tripId: '3',
    detailsUrl: '/trips/3',
    price: '99',
    destination: 'Codesmith Farm',
    dogs: [],
    owners: [],
    date: '08/15/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Codesmith Farm', '4PM Amish Museum', '6PM Back to NYC'],
  },
  {
    title: 'Leaf peep',
    imageUrl: 'https://theknow.denverpost.com/wp-content/uploads/2018/09/Changing-fall-colors-_HHR6121.jpg',
    tripId: '4',
    detailsUrl: '/trips/4',
    price: '99',
    destination: 'Vermont Park',
    dogs: [],
    owners: [],
    date: '09/22/20-09/24/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Codesmith Farm', '4PM Amish Museum', '6PM Back to NYC'],
  },
  {
    title: 'To The Snow',
    imageUrl: 'https://www.voyageavectonchien.com/wp-content/uploads/2017/12/chien_ski_profil-1-980x700.x69756.jpg',
    tripId: '5',
    detailsUrl: '/trips/5',
    price: '99',
    destination: 'Winterfell',
    dogs: [],
    owners: [],
    date: '12/22/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Codesmith Farm', '4PM Amish Museum', '6PM Back to NYC'],
  },
  {
    title: 'Just Go Swim',
    imageUrl: 'https://www.sciencenews.org/wp-content/uploads/2014/01/sm_iStock_000014381823Large_free-1.jpg',
    tripId: '6',
    detailsUrl: '/trips/6',
    price: '99',
    destination: 'Westeros',
    dogs: [],
    owners: [],
    date: '08/28/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Codesmith Farm', '4PM Amish Museum', '6PM Back to NYC'],
  },
  {
    title: 'Pick Some Apples',
    imageUrl: 'https://107fclzizww4ftn03ydjxa1a-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/apples.jpg',
    tripId: '7',
    detailsUrl: '/trips/7',
    price: '99',
    destination: 'Codesmith Farm',
    dogs: [],
    owners: [],
    date: '08/15/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Codesmith Farm', '4PM Amish Museum', '6PM Back to NYC'],
  },
  {
    title: 'Leaf peep',
    imageUrl: 'https://i.pinimg.com/originals/1c/a0/4f/1ca04f5e9ebc935cc921cfd9ff33924b.jpg',
    tripId: '8',
    detailsUrl: '/trips/8',
    price: '99',
    destination: 'Vermont Park',
    dogs: [],
    owners: [],
    date: '09/22/20-09/24/20',
    schedule: ['8AM Depart from Midtown', '10AM Start Hiking', '12PM Picnic', '2PM Codesmith Farm', '4PM Amish Museum', '6PM Back to NYC'],
  },
];

// { id, petName, imageUrl, age, breed, intro }
const dogsList = [
  {
    petName: 'Java',
    id: 'm00',
    age: 3,
    gender: 'male',
    breed: 'corgi',
    imageUrl: 'https://assets.blog.slice.ca/imageserve/wp-content/uploads/2019/01/10142947/cute-dog-names-ideas-cardi/x.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Ruby',
    id: 'f10',
    age: 3,
    gender: 'female',
    breed: 'Golden Retriever',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/best-dog-quotes-1580508958.jpg?crop=0.670xw:1.00xh;0.167xw,0&resize=640:*',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Python',
    id: 'f20',
    age: 2,
    gender: 'female',
    breed: 'Shiba',
    imageUrl: 'https://i.pinimg.com/736x/ae/c4/53/aec453161b2f33ffc6219d8a758307a9.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Bear',
    id: 'm20',
    age: 3,
    gender: 'male',
    breed: 'French Bulldog',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS97WzuAFFvKpXucpDQ1iDNOGl_AGV-BKs8NQ&usqp=CAU',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Fetch',
    id: 'f30',
    age: 2,
    gender: 'female',
    breed: 'Golden Retriever',
    imageUrl: 'https://www.goodnet.org/photos/281x197/31640_hd.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Recursion',
    id: 'm30',
    age: 2,
    gender: 'male',
    breed: 'corgi',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSFNpUN-gA_T47EP5wU0twV4ly2v2G5Rwz7JQ&usqp=CAU',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Redux',
    id: 'f40',
    age: 2,
    gender: 'female',
    breed: 'Shiba',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmoCWYuhcwzrnrmsTYzHwpW1kjvq2cEQMydA&usqp=CAU',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'SASS',
    id: 'm40',
    age: 2,
    gender: 'male',
    breed: 'French Bulldog',
    imageUrl: 'https://imgix.theurbanlist.com/content/article/dogs-to-follow-on-instagram.png?auto=format,compress&w=520&h=390&fit=crop',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Webpack',
    id: 'f50',
    age: 2,
    gender: 'male',
    breed: 'French Bulldog',
    imageUrl: 'https://www.benjerry.com/files/live/sites/systemsite/files/whats-new/3586-dogs/dog-1b.jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
  {
    petName: 'Sequal',
    id: 'm50',
    age: 3,
    gender: 'male',
    breed: 'French Bulldog',
    imageUrl: 'https://img.freepik.com/free-photo/adorable-cute-dog-couch_23-2148567061.jpg?size=338&ext=jpg',
    intro: 'Hello! My name is Anna and I love my corgi a lot. I love reading and outdoor activities. Let\'s chat!',
  },
];

module.exports = { ownersList, tripsList, dogsList };
